before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: mmxca
    name: golang-helloworld
brews:
- tap:
    owner: mmxca
    name: homebrew-tap
  name: golang-helloworld
  homepage: "https://github.com/mmxca/golang-helloworld"
  description: "Simple Hello World Script"
  folder: Formula
  install: |
    bin.install "golang-helloworld"
  test: |
    assert_match /Hello, world./, shell_output("#{bin}/golang-helloworld", 0)